FROM node:23-alpine

WORKDIR /usr/src/app

ARG DATABASE_URL

RUN corepack enable && corepack prepare pnpm@9.15.1 --activate

COPY ./packages ./packages

COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./package.json ./package.json
COPY  turbo.json turbo.json

COPY ./apps/web ./apps/web

RUN pnpm install
RUN pnpm --filter db... run db:generate
RUN DATABASE_URL=${DATABASE_URL} && pnpm run build:web


EXPOSE 3001

CMD ["pnpm", "run", "start:web"]
