import "@ui/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "../components/providers/theme-provider";
import AppBar from "../components/globals/appbar";
import { Toaster } from "@ui/components/ui/sonner";

// const inter = Inter({ subsets: ["latin"] });
const luckiestGuy = Inter({ subsets: ["latin"], weight: "400" });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressContentEditableWarning suppressHydrationWarning>
      <body className={luckiestGuy.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AppBar />
          {children}
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
